# Generated by Django 5.2.11 on 2026-02-12 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "currency",
                    models.CharField(
                        choices=[("NGN", "Nigerian Naira"), ("USD", "US Dollar")],
                        default="NGN",
                        max_length=3,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "alert_threshold",
                    models.DecimalField(decimal_places=2, default=0.8, max_digits=5),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
