# Generated by Django 5.2.11 on 2026-02-12 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinancialSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_for_date", models.DateField()),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_expense",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
