# Generated by Django 5.2.11 on 2026-02-12 19:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("NGN", "Nigerian Naira"), ("USD", "US Dollar")],
                        default="NGN",
                        max_length=3,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings"),
                            ("debt", "Debt Payoff"),
                            ("purchase", "Planned Purchase"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_achieved", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
